(() => {
'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const intro=$('#intro'),space=$('#space'),canvas=$('#gl'),music=$('#music');
const state={yaw:0,pitch:.62,zoom:10.2,targetYaw:0,targetPitch:.62,targetZoom:7.0,drag:false,pointerId:null,lastX:0,lastY:0,lastTime:0,velX:0,velY:0,pinch:0,pointers:new Map(),time:0,started:false,gyro:false};
const words=['NUESTRO UNIVERSO','SIEMPRE JUNTOS','ERES MAGIA','TE ADORO','MI AMOR ETERNO','MI VIDA','PARA TI','AMOR DE MI VIDA','ANGIE ♥ JAZ','ALONSO ∞ ANGIE','LO BONITO DE NOSOTROS','DONDE ESTÉS, HAY LUZ'];
const photoData=[
 ['assets/fotos/angie_pintura.png','Angie, si pudiera pintar un lugar donde guardar lo más bonito, tendría tus ojos, tu sonrisa y esa calma que dejas cuando apareces.'],
 ['assets/fotos/angie_01.jpg','Hay sonrisas que iluminan una habitación; la tuya hace algo más: convierte cualquier instante en un recuerdo que quiero conservar.'],
 ['assets/fotos/angie_02.jpg','Entre millones de caminos, qué bonito es coincidir contigo y descubrir que algunos encuentros parecen escritos por las estrellas.'],
 ['assets/fotos/angie_03.jpg','Tu forma de mirar el mundo tiene algo de poema: sencilla, sincera y capaz de volver especial hasta el día más común.'],
 ['assets/fotos/alonso.jpg','Este universo guarda dos nombres y una historia: Alonso y Angie, caminando entre recuerdos que merecen quedarse para siempre.']
];
const starPoems=[
 'Angie, si el cielo tuviera memoria, llenaría sus estrellas con cada instante bonito que has dejado en mi camino.',
 'A veces pienso que las estrellas no brillan solas; quizá aprendieron de esa luz tranquila que llevas contigo.',
 'Que la vida nos encuentre muchas veces, en lugares distintos, pero con la misma ilusión de seguir compartiendo momentos.',
 'Hay personas que llegan como casualidad y terminan pareciendo destino. Tú eres uno de esos regalos inesperados.',
 'Si pudiera guardar un deseo dentro de cada estrella, pediría que nunca se pierda la ternura de nuestra historia.',
 'Tu nombre cabe en cualquier galaxia, pero en mi universo siempre ocupa el lugar que ninguna otra estrella puede llenar.',
 'Quiero que cada recuerdo bonito tenga un pequeño cielo donde vivir; por eso este universo lleva algo de ti.',
 'Entre nebulosas, cometas y constelaciones, mi rincón favorito sigue siendo cualquier instante que puedo compartir contigo.'
];
const charNames=['Bob Esponja','Elefante','Jirafa','Nutria','Mike Wazowski'];
let gl=null,prog=null,buf=null,pts=[],heartPts=[],burstPts=[],heartStartedAt=0;
function clamp(v,a,b){return Math.max(a,Math.min(b,v))} function lerp(a,b,t){return a+(b-a)*t} function randn(){return Math.random()*2-1}
function toast(text,ms=3400){const t=$('#toast');t.textContent=text;t.classList.add('toast-on');clearTimeout(toast.timer);toast.timer=setTimeout(()=>t.classList.remove('toast-on'),ms)}
function start(){
 if(state.started)return; state.started=true; intro.classList.remove('active'); space.classList.add('active'); space.setAttribute('aria-hidden','false'); heartStartedAt=performance.now();
 buildUI(); initGL(); bindControls();
 music.volume=.72; const p=music.play(); if(p&&p.catch)p.catch(()=>toast('Agrega a-donde-vamos.mp3 dentro de assets/audio para escuchar la canción.'));
 requestAnimationFrame(loop);
}
$('#enterBtn').addEventListener('pointerup',e=>{e.preventDefault();start()});
function buildUI(){
 const ow=$('#orbitWords'); words.forEach((w,i)=>{const e=document.createElement('div');e.className='orbit-word '+(i%4===0?'big ':'')+(i%5===0?'soft':'');e.textContent=w;ow.appendChild(e)});
 const cards=$('#cards');photoData.forEach((p,i)=>{const d=document.createElement('div');d.className='photo-card';d.dataset.i=i;const img=new Image();img.src=p[0];img.alt='Recuerdo '+(i+1);d.appendChild(img);const tag=document.createElement('div');tag.className='photo-tag';tag.textContent=i===4?'ALONSO · ANGIE':'RECUERDO '+(i+1);d.appendChild(tag);d.addEventListener('pointerup',e=>{e.preventDefault();e.stopPropagation();openPhotoPoem(d,p[1],i)});cards.appendChild(d)});
 const stars=$('#stars2d');for(let i=0;i<30;i++){const d=document.createElement('button');d.className='interactive-star';d.type='button';d.textContent='✦';d.dataset.i=i;d.addEventListener('pointerup',e=>{e.preventDefault();e.stopPropagation();const r=canvas.getBoundingClientRect();spawnStarFX((e.clientX-r.left)/r.width*100,(e.clientY-r.top)/r.height*100,i);});stars.appendChild(d)}
 const chars=$('#characters');const specs=[['Bob Esponja',bobSVG],['Elefante',elephantSVG],['Jirafa',giraffeSVG],['Nutria',otterSVG],['Mike Wazowski',mikeSVG]];specs.forEach(([name,svg],i)=>{const d=document.createElement('div');d.className='char';d.dataset.i=i;d.innerHTML=svg+'<div class="char-name">'+name+'</div>';d.addEventListener('pointerup',e=>{e.preventDefault();e.stopPropagation();toast(charMessage(name));burstScreen(e.clientX,e.clientY,28)});chars.appendChild(d)});
 $('#heartHit').addEventListener('pointerup',e=>{e.preventDefault();e.stopPropagation();const m=$('#heartMessage');m.classList.remove('heart-visible');void m.offsetWidth;m.classList.add('heart-visible');burstScreen(e.clientX,e.clientY,180);toast('te quiero angie',2800)});
}
function openPhotoPoem(card,text,i){card.classList.add('hidden');const layer=$('#poemLayer');const box=document.createElement('div');box.className='photo-poem';box.innerHTML='<div class="poem-kicker">UN RECUERDO PARA ANGIE</div><div class="poem-text">'+escapeHTML(text)+'</div><div class="poem-name">ANGIE · JAZ ∞ ALONSO</div>';layer.appendChild(box);burstScreen(innerWidth/2,innerHeight/2,70);setTimeout(()=>box.remove(),4900)}
function escapeHTML(s){return s.replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function charMessage(n){return ({'Bob Esponja':'Hasta las aventuras más sencillas se vuelven bonitas cuando tienen un pedacito de tu alegría.','Elefante':'Hay recuerdos que pesan en el corazón de la forma más bonita: porque significan mucho.','Jirafa':'Me gusta imaginar que desde cualquier altura del universo siempre encontraríamos una forma de volver a coincidir.','Nutria':'Que nunca nos falten momentos pequeños, risas inesperadas y esa ternura que hace especial cualquier tarde.','Mike Wazowski':'Hasta los universos más extraños necesitan una mirada divertida para sentirse completos.'})[n]}
function spawnStarFX(px,py,i){spawnTulips(px,py,i%2?'yellow':'pink');burstScreen(px/100*innerWidth,py/100*innerHeight,80);toast(starPoems[i%starPoems.length],4200)}
function spawnTulips(px,py,color){const holder=$('#tulips');for(let i=0;i<4;i++){const d=document.createElement('div');d.className='tulip';d.style.left=(px+(Math.random()-.5)*16)+'%';d.style.top=(py+(Math.random()-.5)*11)+'%';d.style.color=color==='pink'?'#ff4eaf':'#ffd84a';d.innerHTML=tulipSVG(color);holder.appendChild(d);setTimeout(()=>d.remove(),2900)}}
function tulipSVG(c){const flower=c==='pink'?'#ff4eaf':'#ffd84a';return `<svg viewBox="0 0 60 110"><path d="M30 57C29 72 30 87 30 104" fill="none" stroke="#55a85d" stroke-width="4"/><path d="M30 83C17 77 11 82 8 91C19 91 27 89 30 86" fill="#55a85d"/><path d="M31 72C43 65 49 70 52 78C42 79 35 77 31 74" fill="#55a85d"/><path d="M8 18C11 2 23 9 30 20C37 8 49 2 52 18C55 34 45 52 30 58C15 52 5 34 8 18Z" fill="${flower}" stroke="rgba(255,255,255,.55)" stroke-width="1.5"/><path d="M30 20C28 31 29 45 30 55C33 42 34 30 30 20Z" fill="rgba(255,255,255,.18)"/></svg>`}
function bindControls(){
 $('#musicBtn').addEventListener('pointerup',e=>{e.preventDefault();if(music.paused){music.play().catch(()=>toast('No se encontró a-donde-vamos.mp3.'));$('#musicBtn').textContent='❚❚'}else{music.pause();$('#musicBtn').textContent='♫'}});
 music.addEventListener('play',()=>$('#musicBtn').textContent='❚❚');music.addEventListener('pause',()=>$('#musicBtn').textContent='♫');
 $('#centerBtn').addEventListener('pointerup',e=>{e.preventDefault();state.targetYaw=0;state.targetPitch=.62;state.targetZoom=7});$('#vrBtn').addEventListener('pointerup',e=>{e.preventDefault();enableGyro()});
 const ps=state.pointers;
 canvas.addEventListener('pointerdown',e=>{if(e.pointerType==='mouse'&&e.button!==0)return;e.preventDefault();ps.set(e.pointerId,{x:e.clientX,y:e.clientY});if(ps.size===1){state.drag=true;state.pointerId=e.pointerId;state.lastX=e.clientX;state.lastY=e.clientY;state.lastTime=performance.now();canvas.setPointerCapture?.(e.pointerId)}else if(ps.size===2){const a=[...ps.values()];state.pinch=Math.hypot(a[0].x-a[1].x,a[0].y-a[1].y);state.drag=false}} ,{passive:false});
 canvas.addEventListener('pointermove',e=>{if(!ps.has(e.pointerId))return;e.preventDefault();ps.set(e.pointerId,{x:e.clientX,y:e.clientY});if(ps.size===2){const a=[...ps.values()];const d=Math.hypot(a[0].x-a[1].x,a[0].y-a[1].y);if(state.pinch){state.targetZoom=clamp(state.targetZoom-(d-state.pinch)*.022,3.2,13);state.pinch=d}return}if(!state.drag||e.pointerId!==state.pointerId)return;const now=performance.now(),dt=Math.max(8,now-state.lastTime);const dx=e.clientX-state.lastX,dy=e.clientY-state.lastY;state.targetYaw+=dx*.008;state.targetPitch=clamp(state.targetPitch+dy*.006,-.95,1.2);state.velX=dx/dt;state.velY=dy/dt;state.lastX=e.clientX;state.lastY=e.clientY;state.lastTime=now},{passive:false});
 const end=e=>{ps.delete(e.pointerId);if(e.pointerId===state.pointerId){state.drag=false;state.pointerId=null}if(ps.size<2)state.pinch=0};canvas.addEventListener('pointerup',end,{passive:false});canvas.addEventListener('pointercancel',end,{passive:false});canvas.addEventListener('wheel',e=>{e.preventDefault();state.targetZoom=clamp(state.targetZoom+e.deltaY*.008,3.2,13)},{passive:false});
}
function burstScreen(x,y,n){const h=$('#tulips');for(let i=0;i<n/10;i++){const s=document.createElement('i');s.className='spark';s.style.left=x+'px';s.style.top=y+'px';s.style.setProperty('--sx',(Math.random()*140-70)+'px');s.style.setProperty('--sy',(Math.random()*140-70)+'px');h.appendChild(s);setTimeout(()=>s.remove(),950)}}
function initGL(){
 try{gl=canvas.getContext('webgl',{alpha:false,antialias:true,preserveDrawingBuffer:false});if(!gl){toast('WebGL no está disponible en este navegador.');return}}
 catch(e){toast('No se pudo iniciar el espacio 3D.');return}
 const vs=`attribute vec3 a;attribute float s;attribute float al;uniform mat4 mvp;varying float v;void main(){gl_Position=mvp*vec4(a,1.0);gl_PointSize=s*(260.0/-gl_Position.z);v=al;}`;
 const fs=`precision mediump float;uniform vec3 c;varying float v;void main(){vec2 q=gl_PointCoord-.5;float d=length(q);float a=smoothstep(.5,.03,d)*v;if(a<.01)discard;gl_FragColor=vec4(c,a);}`;
 prog=link(vs,fs);buf=gl.createBuffer();makePoints();resize();window.addEventListener('resize',resize);gl.enable(gl.BLEND);gl.blendFunc(gl.SRC_ALPHA,gl.ONE);gl.disable(gl.DEPTH_TEST);
}
function link(vs,fs){function sh(t,s){const x=gl.createShader(t);gl.shaderSource(x,s);gl.compileShader(x);if(!gl.getShaderParameter(x,gl.COMPILE_STATUS))throw new Error(gl.getShaderInfoLog(x));return x}const p=gl.createProgram();gl.attachShader(p,sh(gl.VERTEX_SHADER,vs));gl.attachShader(p,sh(gl.FRAGMENT_SHADER,fs));gl.linkProgram(p);if(!gl.getProgramParameter(p,gl.LINK_STATUS))throw new Error(gl.getProgramInfoLog(p));return p}
function makePoints(){pts=[];for(let i=0;i<12500;i++){const a=Math.random()*Math.PI*2;const r=Math.pow(Math.random(),.56)*5.5;const arm=Math.sin(a*3.0+r*1.4)*.28;const rr=r+arm;pts.push({x:Math.cos(a)*rr,y:randn()*(.06+r*.055),z:Math.sin(a)*rr,s:1.0+Math.random()*3.7,a:.25+Math.random()*.75})}for(let i=0;i<3300;i++){const a=Math.random()*Math.PI*2,r=5.8+Math.random()*7.5;pts.push({x:Math.cos(a)*r,y:randn()*4.5,z:Math.sin(a)*r,s:.7+Math.random()*2.8,a:.12+Math.random()*.45})}heartPts=[];for(let i=0;i<2400;i++){const t=Math.random()*Math.PI*2;const x=16*Math.pow(Math.sin(t),3),y=13*Math.cos(t)-5*Math.cos(2*t)-2*Math.cos(3*t)-Math.cos(4*t);const edge=0.82+Math.random()*.22;heartPts.push({x:x*.115*edge,y:y*.115*edge,z:randn()*.13,s:1.4+Math.random()*3.7,a:.55+Math.random()*.45})}}
function resize(){canvas.width=Math.max(1,Math.floor(innerWidth*devicePixelRatio));canvas.height=Math.max(1,Math.floor(innerHeight*devicePixelRatio));if(gl)gl.viewport(0,0,canvas.width,canvas.height)}
function matMul(a,b){const o=new Float32Array(16);for(let c=0;c<4;c++)for(let r=0;r<4;r++)o[c*4+r]=a[r]*b[c*4]+a[4+r]*b[c*4+1]+a[8+r]*b[c*4+2]+a[12+r]*b[c*4+3];return o}
function perspective(fov,asp,n,f){const q=1/Math.tan(fov/2),nf=1/(n-f);return new Float32Array([q/asp,0,0,0,0,q,0,0,0,0,(f+n)*nf,-1,0,0,2*f*n*nf,0])}
function rotY(a){const c=Math.cos(a),s=Math.sin(a);return new Float32Array([c,0,-s,0,0,1,0,0,s,0,c,0,0,0,0,1])}
function rotX(a){const c=Math.cos(a),s=Math.sin(a);return new Float32Array([1,0,0,0,0,c,s,0,0,-s,c,0,0,0,0,1])}
function trans(z){return new Float32Array([1,0,0,0,0,1,0,0,0,0,1,0,0,0,z,1])}
function drawSet(arr,mvp,color){const data=new Float32Array(arr.length*5);for(let i=0;i<arr.length;i++){const p=arr[i];data.set([p.x,p.y,p.z,p.s,p.a],i*5)}gl.bindBuffer(gl.ARRAY_BUFFER,buf);gl.bufferData(gl.ARRAY_BUFFER,data,gl.DYNAMIC_DRAW);gl.useProgram(prog);const ap=gl.getAttribLocation(prog,'a'),sp=gl.getAttribLocation(prog,'s'),al=gl.getAttribLocation(prog,'al');gl.enableVertexAttribArray(ap);gl.vertexAttribPointer(ap,3,gl.FLOAT,false,20,0);gl.enableVertexAttribArray(sp);gl.vertexAttribPointer(sp,1,gl.FLOAT,false,20,12);gl.enableVertexAttribArray(al);gl.vertexAttribPointer(al,1,gl.FLOAT,false,20,16);gl.uniformMatrix4fv(gl.getUniformLocation(prog,'mvp'),false,mvp);gl.uniform3fv(gl.getUniformLocation(prog,'c'),color);gl.drawArrays(gl.POINTS,0,arr.length)}
function burst3D(n){for(let i=0;i<n;i++){const a=Math.random()*Math.PI*2,b=Math.acos(randn()),v=.7+Math.random()*3;burstPts.push({x:0,y:0,z:0,s:2+Math.random()*4,a:1,vx:Math.sin(b)*Math.cos(a)*v,vy:Math.cos(b)*v,vz:Math.sin(b)*Math.sin(a)*v,life:1})}}
function updateBursts(dt){for(let i=burstPts.length-1;i>=0;i--){const p=burstPts[i];p.x+=p.vx*dt;p.y+=p.vy*dt;p.z+=p.vz*dt;p.vy-=.7*dt;p.life-=dt*.7;p.a=p.life;if(p.life<=0)burstPts.splice(i,1)}}
function loop(ts){state.time=ts*.001;state.yaw=lerp(state.yaw,state.targetYaw,.075);state.pitch=lerp(state.pitch,state.targetPitch,.075);state.zoom=lerp(state.zoom,state.targetZoom,.09);if(!state.drag&&Math.abs(state.velX)>.001){state.targetYaw+=state.velX*.45;state.velX*=.92}updateBursts(.016);render();layout3D();requestAnimationFrame(loop)}
function render(){if(!gl)return;gl.clearColor(.001,0,.004,1);gl.clear(gl.COLOR_BUFFER_BIT);const asp=canvas.width/canvas.height;let m=matMul(perspective(.8,asp,.1,70),trans(-state.zoom));m=matMul(m,rotX(state.pitch));m=matMul(m,rotY(state.yaw+state.time*.018));drawSet(pts,m,[1,.035,.40]);const progress=clamp((performance.now()-heartStartedAt-600)/5200,0,1);if(progress>0)drawSet(heartPts.slice(0,Math.max(1,Math.floor(heartPts.length*progress))),matMul(m,trans(-.35)),[1,.19,.68]);if(burstPts.length)drawSet(burstPts,m,[1,.5,.85])}
function project(x,y,z){const cy=Math.cos(state.yaw),sy=Math.sin(state.yaw),cx=Math.cos(state.pitch),sx=Math.sin(state.pitch);let X=x*cy-z*sy,Z=x*sy+z*cy,Y=y*cx-Z*sx;Z=y*sx+Z*cx;const scale=1/(state.zoom+Z);return{x:50+X*47*scale,y:50-Y*47*scale,depth:Z}}
function layout3D(){const t=state.time;$$('.interactive-star').forEach((e,i)=>{const a=t*.045+i*Math.PI*2/30,r=4.7+(i%5)*.38,p=project(Math.cos(a)*r,Math.sin(a*1.55)*1.05,Math.sin(a)*r);e.style.left=p.x+'%';e.style.top=p.y+'%';e.style.zIndex=String(Math.round(400-p.depth*10));e.style.opacity=String(clamp(.22+(7-p.depth)/8,.2,1));e.style.transform=`translate(-50%,-50%) scale(${clamp(1.25-p.depth*.045,.5,1.25)})`});
 $$('.orbit-word').forEach((e,i)=>{const a=t*.13+i*Math.PI*2/words.length,r=3.5+(i%3)*.6,p=project(Math.cos(a)*r,.35*Math.sin(a*1.4),Math.sin(a)*r);e.style.left=p.x+'%';e.style.top=(p.y+4)+'%';e.style.zIndex=String(Math.round(180-p.depth*6));e.style.opacity=String(clamp(.28+(7-p.depth)/9,.25,1))});
 $$('.photo-card').forEach((e,i)=>{const a=t*.055+i*Math.PI*2/photoData.length,r=3.05,p=project(Math.cos(a)*r,.7*Math.sin(a*1.3),Math.sin(a)*r);e.style.left=p.x+'%';e.style.top=p.y+'%';e.style.zIndex=String(Math.round(250-p.depth*9));e.style.transform=`translate(-50%,-50%) rotateY(${(-state.yaw-a)*25}deg) rotateZ(${Math.sin(a)*5}deg) scale(${clamp(1.13-p.depth*.075,.68,1.18)})`});
 $$('.char').forEach((e,i)=>{const a=-t*.085+i*Math.PI*2/charNames.length,r=4.6,p=project(Math.cos(a)*r,.85*Math.sin(t*.65+i),Math.sin(a)*r);e.style.left=p.x+'%';e.style.top=p.y+'%';e.style.zIndex=String(Math.round(210-p.depth*8));e.style.transform=`translate(-50%,-50%) translateZ(${Math.max(-50,40-p.depth*8)}px) rotateY(${Math.sin(t+i)*8}deg)`})}
async function enableGyro(){if(!('DeviceOrientationEvent'in window)){toast('Este teléfono o navegador no ofrece movimiento por orientación.');return}try{if(typeof DeviceOrientationEvent.requestPermission==='function'){const ok=await DeviceOrientationEvent.requestPermission();if(ok!=='granted'){toast('Permiso de movimiento no concedido.');return}}window.addEventListener('deviceorientation',e=>{if(e.gamma==null)return;state.targetYaw=e.gamma*.022;state.targetPitch=clamp(.62+(e.beta-45)*.008,-.95,1.2)});state.gyro=true;toast('Movimiento activado: inclina el teléfono para mirar alrededor.',3000)}catch(e){toast('No se pudo activar el movimiento del teléfono.')}}
const bobSVG=`<svg viewBox="0 0 100 100"><rect x="27" y="25" width="46" height="47" rx="7" fill="#f7d93a" stroke="#ffef86" stroke-width="2"/><circle cx="42" cy="43" r="7" fill="white"/><circle cx="42" cy="43" r="3"/><circle cx="59" cy="43" r="7" fill="white"/><circle cx="59" cy="43" r="3"/><path d="M39 57Q50 67 62 57" fill="none" stroke="#111" stroke-width="3"/><path d="M32 72l-7 10M68 72l7 10" stroke="#e7c52b" stroke-width="4"/></svg>`;
const elephantSVG=`<svg viewBox="0 0 100 100"><path d="M25 70Q17 53 25 36Q35 20 54 27Q74 25 79 43L77 69L61 72L59 48L47 49L45 72Z" fill="#a7a0b8" stroke="#e1d9ee" stroke-width="2"/><path d="M72 45Q91 45 83 65Q78 73 68 67" fill="#a7a0b8" stroke="#e1d9ee" stroke-width="2"/><circle cx="57" cy="41" r="3"/><circle cx="69" cy="39" r="3"/></svg>`;
const giraffeSVG=`<svg viewBox="0 0 100 100"><path d="M43 74L46 35Q47 17 62 15Q77 15 78 29L74 43L67 40L68 26Q60 22 57 31L55 75Z" fill="#e7b94f" stroke="#ffe29a" stroke-width="2"/><path d="M55 32L67 26M48 49L58 45M49 65L59 61" stroke="#9a5a24" stroke-width="7"/><circle cx="63" cy="22" r="2.5"/><circle cx="73" cy="22" r="2.5"/></svg>`;
const otterSVG=`<svg viewBox="0 0 100 100"><ellipse cx="52" cy="57" rx="25" ry="31" fill="#8b5a3d"/><circle cx="52" cy="34" r="22" fill="#a66a48"/><circle cx="44" cy="31" r="3"/><circle cx="60" cy="31" r="3"/><path d="M47 40Q52 45 57 40" fill="none" stroke="#2a1710" stroke-width="2"/><circle cx="35" cy="26" r="8" fill="#a66a48"/><circle cx="69" cy="26" r="8" fill="#a66a48"/></svg>`;
const mikeSVG=`<svg viewBox="0 0 100 100"><circle cx="50" cy="50" r="31" fill="#72c64b" stroke="#b7f08e" stroke-width="3"/><circle cx="50" cy="43" r="15" fill="white"/><circle cx="50" cy="43" r="6" fill="#111"/><path d="M31 59Q50 72 69 59" fill="none" stroke="#174b16" stroke-width="3"/><path d="M39 67l-5 14M61 67l5 14" stroke="#72c64b" stroke-width="5"/></svg>`;
})();
